apiVersion: batch/v1
kind: Job
metadata:
  name: 365widgets
  namespace: 365widgets
spec:
  template:
    spec:
      containers:
      - name: 365widgets
        image: 365widgets:latest
        command: ["python",  "app/process.py", "logs/example.log"]
        imagePullPolicy: Never
      restartPolicy: Never